version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: esp
    binary: esp
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/AbsolutOD/esp/cmd.version={{.Tag}}
      - -X github.com/AbsolutOD/esp/cmd.commit={{.ShortCommit}}
      - -X github.com/AbsolutOD/esp/cmd.date={{.Date}}

archives:
  - id: esp
    name_template: "esp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: git
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  draft: false
